prathamesh-borse/Hacktoberfest_2021

- Article/README.md
- Article/code.cpp
- README.md
I added 
- Code in C++.
- Explanation in README.md.
- Demo link in README.md.
Please review it.
> An article writen by me about Suffix array of string.

- Java Codes/CheckPalindrome.java
> Adding new Java Code

- leetcode/Easy_Q1464.java
Hey @prathamesh-borse !!
I have added Leetcode Easy Q 1464 Solution in Java
Question : Maximum Product of Two Elements in an Array.
Please review the code & suggest changes if needed
> Added Leetcode Q 1464 (Java Solution)

- leetcode/Q1_TwoSum.cpp
A C++ solution for the first question in LeetCode (Two Sum) is added. Please merge.
> Added a solution to Two Sum Question

- Data Science/covidreport_project.ipynb
- Data Science/covidreports.csv
I have added a Covid 19 Model analysis using DataScience/ML.
> Added a Project

- singly-linked-lists-in-c/LinkedList_deletion.c
- singly-linked-lists-in-c/linked_list.c
- singly-linked-lists-in-c/linkedlist_insertion.c
Linked list insertion , deletion and traversal coded in C language.
1) Insertion at beginning, insertion at end, insertion at an index
and insertion after a node.
2) Deletion at beginning, deletion at end, deletion at an index
and  delete a node.
3) Traversal from head node to end.
> Linked List insertion, traversal and deletion in C

- leetcode/Easy_Q771.java
I have added LeetCode Easy Q771 Jewels & Stones.
Language Used : Java
> Added Leetcode Q 771 (Java Solution)

- basic tic-tac-toe/index.html
- basic tic-tac-toe/main.js
- basic tic-tac-toe/style.css
added a basic tic-tac-toe game created using basic html, css and javascript.
> Added basic tic-tac-toe game

- leetcode/Easy_Q1464.java
- leetcode/Easy_Q852.java
Hey @prathamesh-borse ,
I have added Leetcode Q852 & added the link to Q1464.
Please review the changes. 
Thank You!
> Added LeetCode Q852 & Added Link to Q1464

- README.md
Dear, @prathamesh-borse I have added my profile. Please check and review it!
> Added my profile!

- README.md
Halo,
please merge my PR to your repo.
Thank you
> Added myself to the contributors

- leetcode/36_Valid_Sudoku.cpp
<a href="https://leetcode.com/problems/valid-sudoku/">Problem Link</a>
Added the solution of the above problem
> Adding solution of Leetcode problem number 36

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/chore.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/other.yml
- .github/PULL_REQUEST_TEMPLATE.md
Added GitHub Issue and PR Template for More Enhancement of this Project .! ⚡ 💯
> Added ISSUE and PR Template

- README.md
I have added my profile in this repository.
Closes #XXXXX
> Added a Profile!

- Data Science/SalesAnalysis.ipynb
We can understand how the analysis will done with sales data with help of data science
> Sales Analysis using pandas and numpy

- Java Codes/SlidingWindowMaximum.java
Question no. 239 on leetcode ----  https://leetcode.com/problems/sliding-window-maximum/
> added Sliding window algo in java

- Java Codes/isomorphicstrings.java
question link:- https://practice.geeksforgeeks.org/problems/isomorphic-strings-1587115620/1
> added how to check if two strings are isomorphics or not

- Java Codes/Bucket Sort.java
Created Bucket Sort program
Closes #XXXXX
> Create Bucket Sort.java

- C++ Programs/factorial of large number.cpp
Adding C++ program along with problem link in the file
Closes #XXXXX
> Create factorial of large number.cpp

- README.md
I have added my profile in readme folder!
Closes #XXXXX
> Added my Profile Link!

- Java Codes/DetectLoopInLinkedList.java
This Algorithm is also known as Floyd's cycle finding algorithm.
Closes #XXXXX
> Added an Algo Detect a Loop In Linked List
